### PR TITLE
Replace use of Azure queues and wrapping of async tasks with celery tasks

### PR DESCRIPTION
**Pull request by c-w**
Copy of https://github.com/ascoderu/opwen-cloudserver/pull/67 submitted by @adamsclafani.

Note: Celery has not been wired in with Docker and the old ambassador system has not been unwired yet.

Instructions:
1.) Rabbitmq must be installed via ones package manager.
2.) pip install celery to the venv
3.) afterwards run "rabbitmq-server" in a new shell window (for stoppage enter: "rabbitmqctl stop")
4.) from the opwen-cloudserver directory, run: "celery -A opwen_email_server.celery.celery worker -l debug" to start up the celery worker

Resolves https://github.com/ascoderu/opwen-cloudserver/issues/45

### CODE REVIEW

**Comment by c-w** [comment]
Hey @adamsclafani. I made a few changes to make the continuous integration pass and to wire-up Celery into docker-compose and the makefile. You should be able to push to this branch `celery`, but note that you'll have to re-clone the repo or add this remote: `git@github.com:ascoderu/opwen-cloudserver.git`.

- [ ] Could you please verify that everything is working as expected with the `docker-compose` and `makefile`?
- [ ] Also, could you please investigate how we can ensure that each of the tasks ends up on its own queue and how we can tell Celery to only run the worker for a particular queue? In this way we can scale the queue consumers independently based on whichever queues have more work (e.g. I'm sure that the email-send queue will be the longest).

Thanks!

**Comment by c-w** [comment]
That should have been fixed in 64b8733 @adamsclafani.

**Comment by adamsclafani** [comment]
worker 1 is reporting: "/app/run-celery.sh: 5: /app/run-celery.sh: worker: not found" when running docker compose

**Comment by adamsclafani** [comment]
worker_1 throwing exception: "ModuleNotFoundError: No module named 'opwen_email_server.services.celery'" which I think is caused by --app pointing to services.celery instead of services.tasks in run-celery.sh

afterwards, worker_1 reports: /app/run-celery.sh: 5: /app/run-celery.sh: worker: not found 
then exits.

**Comment by c-w** [comment]
@adamsclafani Given that this now seems to work reasonably well, I'm going to merge this to avoid the PR getting too huge. Let's do any improvements like the per-task queue as follow-up PRs (you can use feature branches off of this repo since you now have write access). I'll also do a larger piece of work to get our k8s infrastructure updated before the next release.

**Comment by c-w** [comment]
Merged this manually in https://github.com/ascoderu/opwen-cloudserver/commit/14beff038d1edc7181f42f672c03f3c3e012ff70 to preserve author information.

**Pull request closed without merging**
